### ISSUE TITLE
Не работает API

### ISSUE THREAD

**Issue by matthewwwz** [eSKond/QuikQtBridge#1]
Здравствуй! Спасибо за крутую либу, все сделал по описанию, но API не работает, никакой ответ не отдает.

Мой конфиг:
`{
  "host": "local",
  "port": 57777,
  "exchangeLogPrefix": "exch",
  "allowedIPs": ["127\\.0\\.0\\.1", "192\\.168\\.0\\.*", "192\\.168\\.2\\.*"]
}
`

Подключался по вебсокету через ws://localhost:57777

**Comment by eSKond** [comment]
стоп, а причем здесь вебсокет? Это обычный сокет

**Comment by matthewwwz** [comment]
> 

пардон, обычный сокет. Как можно отдебажить работу апи?
QUIK - 10.0.1.18

**Comment by eSKond** [comment]
на чем пишете то? Собственно дебажить как любое приложение работающее с сокетом

**Comment by tashik** [comment]
написав клиента к API, а как еще? В репозитории лежит набросок клиента на python:
https://github.com/eSKond/QuikQtBridge/tree/master/example - вот тут. Запустите его.

**Comment by matthewwwz** [comment]
> на чем пишете то? Собственно дебажить как любое приложение работающее с сокетом

Golang

**Comment by eSKond** [comment]
Ну там вроде должно быть всё просто, просто берите пример питоновский и по аналогии с ним делайте клиента.

**Comment by tashik** [comment]
В директории с квиком создаем папку Bridge, туда кладем содержимое папок bin и lua из этого репа. Дальше на golang пишем клиента по аналогии с тем, что на python написан (в репе папка example). Дальше в квике запускаем lua-скрипт (в конфиге проверяем пути до dll), запускаем клиента - и все буде добре

**Comment by matthewwwz** [comment]
> В директории с квиком создаем папку Bridge, туда кладем содержимое папок bin и lua из этого репа. Дальше на golang пишем клиента по аналогии с тем, что на python написан (в репе папка example). Дальше в квике запускаем lua-скрипт (в конфиге проверяем пути до dll), запускаем клиента - и все буде добре

спасибо за инфу

**Comment by eSKond** [comment]
Протокол там довольно простой, по сути он пытается просто вычленить из входящего потока json пакет. Ну а отправка запросов вообще элементарна - берём json и текстом его в сокет запихиваем

**Comment by eSKond** [comment]
Если речь об отладке самой dll, то с некоторого момента квик запрещает загружаться под отладчиком, поэтому никак

**Comment by eSKond** [comment]
Ещё на винде нужно брандмауер проверить, чтобы порт был открыт
