### ISSUE TITLE
Долбоёбский вопрос

### ISSUE THREAD

**Issue by PavelXWX** [eSKond/QuikQtBridge#2]
Есть ли методы в апи по получению всей клиентсой информации(баланс, история сделок и т.д.), возможность входа/выхода из сделок, получение новостей и отправка заявок на вывод средств. Спасибо

**Comment by tashik** [comment]
http://www.bot4sale.ru/images/FILES/QLua/CHM/QLUA/title.htm - мост это обёртка над вот этим. Можно отправить только те команды, которые умеет QLUA.

**Comment by eSKond** [comment]
Ну или по-другому: смотрите документацию квика по LUA API - эта библиотека просто позволяет делать эти вызовы путём отправки JSON запросов, в самой библиотеке знание апи не зашито, в этом и преимущество - при изменении апи, саму библиотеку менять не нужно, нужно менять только запросы, которые вы отправляете

**Comment by PavelXWX** [comment]
Спасибо, да прибудет с вами сила!
