### ISSUE TITLE
Feature request - split json stream with \r \n

### ISSUE THREAD

**Issue by 0LEG0** [eSKond/QuikQtBridge#3]
Делаю биндинги к java через сокет. Считаю, что было бы намного удобнее парсить поток данных из сокета, если бы json ответы(запросы) были отделены друг от друга CR или LF или CRLF.
Спасибо.

**Comment by eSKond** [comment]
Будет время гляну (на следующей неделе постараюсь) - не хотелось бы поломать парсинг тем, кто уже использует бридж. Но вообще алгоритм парсинга можете подсмотреть в примере питоновском - он легко читаемый даже если вы питон не знаете.

**Comment by tashik** [comment]
Сергей, если будете делать, сделайте это через настройку в конфиге - мне не нужно отделять ничего ничем, пожалуйста

**Comment by eSKond** [comment]
да, так и планировал

**Comment by 0LEG0** [comment]
Просто хотелось бы убрать футпринт бесполезного кода на посимвольное чтение и подсчет открытых и закрытых скобок. Если бы все JSON сообщения были отделены друг от друга новой строкой, тогда было бы их проще парсить построчно. Изменения на стороне QuikQtBridge не существенные.

**Comment by eSKond** [comment]
а что делать когда вы запросите сообщения биржи и в них будут переносы строк? с точки зрения json это не проблема, с точки зрения такого упрощённого чтения будет "ой"

**Comment by eSKond** [comment]
а, стоп, json же переносы кодирует... в общем подумать надо

**Comment by eSKond** [comment]
так то вообще посимвольное чтение это не бесполезный код, то же самое делается под капотом когда вы вызываете какой-нибудь readLine или что там в java.

**Comment by eSKond** [comment]
ну и чтобы быть совсем точным, чтение из сокета не посимвольное, посимвольный разбор буфера.

**Comment by 0LEG0** [comment]
> а что делать когда вы запросите сообщения биржи и в них будут переносы строк? с точки зрения json это не проблема, с точки зрения такого упрощённого чтения будет "ой"

Вы правы.

**Comment by 0LEG0** [comment]
> так то вообще посимвольное чтение это не бесполезный код, то же самое делается под капотом когда вы вызываете какой-нибудь readLine или что там в java.

примерно так
